name: Update Version File

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string


jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Create and switch to feature branch
        id: create_branch
        run: |
          BRANCH_NAME="update-staging-${{ inputs.version }}-${{ github.run_number }}"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Update version in app-config.yaml
        run: |
          echo "Updating container.version to ${{ inputs.version }} for application ${{ inputs.application }}"
          #sudo apt-get update && sudo apt-get install -y yq
          yq -i '.container.version = "${{ inputs.version }}"' app-config.yaml
          echo "Updated file content:"
          cat app-config.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW_PAT != '' && secrets.WORKFLOW_PAT || secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ steps.create_branch.outputs.branch_name }}
          commit-message: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          title: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          author: "Ravi Kumar <ravikj004@gmail.com>"
          committer: "Ravi Kumar <ravikj004@gmail.com>"
          body: |
            This PR updates the container version in `app-config.yaml` to `${{ inputs.version }}` for application `${{ inputs.application }}`.
          fail-on-error: true
