name: Update Version File

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token1:
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: fun
          fetch-depth: 0

      # - name: Install yq
      #   run: sudo apt-get update && sudo apt-get install -y yq

      - name: Create and switch to feature branch
        id: create_branch
        run: |
          BRANCH_NAME="update-staging-${{ inputs.version }}-${{ github.run_number }}"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Update version in app-config.yaml
        run: |
          echo "Updating container.version to ${{ inputs.version }} for application ${{ inputs.application }}"
          #sudo apt-get update && sudo apt-get install -y yq
          yq -i '.container.version = "${{ inputs.version }}"' app-config.yaml
          echo "Updated file content:"
          cat app-config.yaml

      - name: Push new branch
        run: |
          git config user.name "ravikumara004"
          git config user.email "ravikj004@gmail.com"
          #git remote set-url origin https://ravikumara004:${TOKEN}@github.com/ravikumara004/workflow.git
          git add app-config.yaml
          git commit -m "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }} -f
          git branch
          cat app-config.yaml

      - name: PR
        id: create_pr
        run: |
          PR_RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token1 }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ravikumara004/workflow/pulls \
            -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"${{ steps.create_branch.outputs.branch_name }}","base":"fun"}')

          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Wait for PR Approval
        if: ${{ steps.create_pr.outputs.pr_number != '' }}
        run: |
          echo "Waiting for approval on PR #${{ steps.create_pr.outputs.pr_number }}..."
          APPROVED="false"
          for i in {1..60}; do
            REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.token1 }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/ravikumara004/workflow/pulls/${{ steps.create_pr.outputs.pr_number }}/reviews)

            if echo "$REVIEWS" | jq -e '.[] | select(.state == "APPROVED")' > /dev/null; then
              echo "✅ PR approved!"
              APPROVED="true"
              break
            else
              echo "Still waiting for approval... (check $i/60)"
              sleep 30
            fi
          done

          if [ "$APPROVED" != "true" ]; then
            echo "❌ PR not approved within waiting period (30 mins). Exiting."
            exit 1
          fi

      - name: Merge Pull Request
        if: ${{ steps.create_pr.outputs.pr_number != '' }}
        id: merge_pr
        run: |
          echo "Merging PR #${{ steps.create_pr.outputs.pr_number }}"
          MERGE_RESPONSE=$(curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token1 }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ravikumara004/workflow/pulls/${{ steps.create_pr.outputs.pr_number }}/merge \
            -d '{"merge_method":"squash"}')

      - name: Delete Feature Branch
        if: ${{ success() && steps.create_branch.outputs.branch_name != '' }}
        run: |
          echo "Deleting branch ${{ steps.create_branch.outputs.branch_name }}"
          curl -s -L -X DELETE \
            -H "Authorization: Bearer ${{ secrets.token1 }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ravikumara004/workflow/git/refs/heads/${{ steps.create_branch.outputs.branch_name }}


      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ secrets.token1 }}
      #     base: fun
      #     branch: ${{ steps.create_branch.outputs.branch_name }}
      #     commit-message: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
      #     title: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
      #     author: "Ravi Kumar <ravikj004@gmail.com>"
      #     committer: "Ravi Kumar <ravikj004@gmail.com>"
      #     body: |
      #       This PR updates the container version in `app-config.yaml` to `${{ inputs.version }}` for application `${{ inputs.application }}`.
