name: Update Version File

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Needed to create a new branch from main

      - name: Create and switch to new branch
        id: create_branch
        run: |
          BRANCH_NAME="update-${{ inputs.application }}-${{ inputs.version }}-$(date +%s)"
          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Update version in app-config.yaml
        run: |
          echo "Updating container.version to ${{ inputs.version }} for application ${{ inputs.application }}"
          #sudo apt-get update && sudo apt-get install -y yq
          yq -i '.container.version = "${{ inputs.version }}"' app-config.yaml
          echo "Updated file content:"
          cat app-config.yaml

      - name: Commit and push changes
        run: |
          git config user.name "ravikumara004"
          git config user.email "ravikj004@gmail.com"
          git add app-config.yaml
          git commit -m "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ steps.create_branch.outputs.branch_name }}
          title: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          body: |
            This PR updates the container version in `app-config.yaml` to `${{ inputs.version }}` for application `${{ inputs.application }}`.
