name: Update Version File

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update version in app-config.yaml
        run: |
          echo "Updating container.version to ${{ inputs.version }} for application ${{ inputs.application }}"

          # Using yq for safe YAML editing (recommended)
          #sudo apt-get update && sudo apt-get install -y yq
          yq -i '.container.version = "${{ inputs.version }}"' app-config.yaml

          echo "Updated content:"
          cat app-config.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add app-config.yaml
          git commit -m "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          git push
