name: Update Version File

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: fun
          fetch-depth: 0  # Needed to create a new branch from main
      - name: ls before
        run: |
          ls -l
          cat app-config.yaml

      - name: Create and switch to new branch
        id: create_branch
        run: |
          BRANCH_NAME="update-${{ inputs.application }}-${{ inputs.version }}-$(date +%s)"
          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: ls after
        run: |
          ls -l
          cat app-config.yaml

      - name: Update version in app-config.yaml
        run: |
          echo "Updating container.version to ${{ inputs.version }} for application ${{ inputs.application }}"
          #sudo apt-get update && sudo apt-get install -y yq
          yq -i '.container.version = "${{ inputs.version }}"' app-config.yaml
          echo "Updated file content:"
          cat app-config.yaml

      - name: user.name user.email
        env:
          TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          git config user.name "ravikumara004"
          git config user.email "ravikj004@gmail.com"
          #git remote set-url origin https://ravikumara004:${TOKEN}@github.com/ravikumara004/workflow.git
          git add .
          git commit -m "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }} -f
          git branch
          cat app-config.yaml

      # - name: user.name user.email
      #   env:
      #     TOKEN: ${{ secrets.WORKFLOW_PAT }}
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: token $TOKEN" \
      #       -H "Accept: application/vnd.github+json" \
      #       https://api.github.com/repos/ravikumara004/workflow/pulls \
      #       -d '{
      #         "title": "Update container version to '${{ inputs.version }}' for '${{ inputs.application }}'",
      #         "head": "${{ steps.create_branch.outputs.branch_name }}",
      #         "base": "fun",
      #         "body": "This PR updates the container version in `app-config.yaml` to `'${{ inputs.version }}'` for application `'${{ inputs.application }}'`."
      #       }'

      - name: Create Pull Request via GitHub API
        env:
          TOKEN: ${{ secrets.WORKFLOW_PAT }}
          OWNER: ravikumara004
          REPO: workflow
          VERSION: ${{ inputs.version }}
          APP: ${{ inputs.application }}
          RUN_ID: ${{ github.run_number }}
        run: |
          echo "Creating PR from feature/update-${APP}-${VERSION}-${RUN_ID} to fun..."
          curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER}/${REPO}/pulls \
            -d "{
              \"title\": \"Update container version to ${VERSION} for ${APP}\",
              \"head\": \"feature/update-${APP}-${VERSION}-${RUN_ID}\",
              \"base\": \"fun\",
              \"body\": \"This PR updates the container version in app-config.yaml to ${VERSION} for application ${APP}.\"
            }"
      
          echo "Response:"
          cat response.json

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ secrets.WORKFLOW_PAT || secrets.GITHUB_TOKEN }}
      #     commit-message: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
      #     title: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
      #     branch: ${{ steps.create_branch.outputs.branch_name }}
      #     base: fun
      #     author: "ravikj004@gmail.com"
      #     committer: "ravikj004@gmail.com"
      #     body: |
      #       This PR updates the container version in `app-config.yaml` to `${{ inputs.version }}` for application `${{ inputs.application }}`.

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.WORKFLOW_PAT || secrets.GITHUB_TOKEN }}
      #     base: main
      #     branch: ${{ steps.create_branch.outputs.branch_name }}
      #     title: "Update container version to ${{ inputs.version }} for ${{ inputs.application }}"
      #     body: |
      #       This PR updates the container version in `app-config.yaml` to `${{ inputs.version }}` for application `${{ inputs.application }}`.
